---
driver:
  name: docker

provisioner:
  name: chef_zero
  require_chef_omnibus: false

platforms:
  - name: centos-7.1
    driver_config:
      provision_command:
        - >
          curl -L -O https://www.opscode.com/chef/install.sh &&
          bash install.sh -v <%= ENV.fetch 'CHEF_VERSION', '12.5' %>

suites:
  - name: default
    run_list:
      - recipe[github-test]
    attributes:
      github:
        token: <%= ENV.fetch 'GITHUB_TOKEN' %>
      github-test:
        org: <%= ENV.fetch 'GITHUB_ORG', 'glenjamin-chef-github' %>
